server:
  port: 8084

spring:
  application:
    name: atm-service
  datasource:
    url: jdbc:postgresql://ep-shiny-brook-a1ay3vmn-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_PhTEFJqY85bz&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_PhTEFJqY85bz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: MySecretKeyForFinTrustBankThatIsLongEnoughForHS256Algorithm

feign:
  client:
    transaction-service:
      url: http://localhost:8083
    account-service:
      url: http://localhost:8082
    auth-service:
      url: http://localhost:8081
    customer-service:
      url: http://localhost:8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.fintrust.atm: DEBUG
