server:
  port: 8084

spring:
  application:
    name: atm-service
  datasource:
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

feign:
  client:
    transaction-service:
      url: ${TRANSACTION_SERVICE_URL}
    account-service:
      url: ${ACCOUNT_SERVICE_URL}
    auth-service:
      url: ${AUTH_SERVICE_URL}
    customer-service:
      url: ${CUSTOMER_SERVICE_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.fintrust.atm: DEBUG